# Generated by Django 4.2.4 on 2024-04-26 23:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konten',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('tanggal_rilis', models.DateField()),
                ('tahun', models.IntegerField()),
                ('durasi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NonPremium',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.akun')),
            ],
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('jenis', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PemilikHakCipta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_royalti', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Podcaster',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.akun')),
            ],
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.akun')),
            ],
        ),
        migrations.RemoveField(
            model_name='akun',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='akun',
            name='id',
        ),
        migrations.RemoveField(
            model_name='akun',
            name='name',
        ),
        migrations.AddField(
            model_name='akun',
            name='email',
            field=models.EmailField(default=1, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='akun',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Perempuan'), (1, 'Laki-laki')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='akun',
            name='is_verified',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='akun',
            name='kota_asal',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='akun',
            name='nama',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='akun',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='akun',
            name='tanggal_lahir',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='akun',
            name='tempat_lahir',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id_konten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.konten')),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlaylist',
            fields=[
                ('id_user_playlist', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=500)),
                ('jumlah_lagu', models.IntegerField()),
                ('tanggal_dibuat', models.DateField()),
                ('total_durasi', models.IntegerField()),
                ('email_pembuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.akun')),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_dimulai', models.DateTimeField()),
                ('timestamp_berakhir', models.DateTimeField()),
                ('metode_bayar', models.CharField(max_length=50)),
                ('nominal', models.IntegerField()),
                ('email_akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.akun')),
                ('jenis_paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paket')),
            ],
        ),
        migrations.CreateModel(
            name='Songwriter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.akun')),
                ('id_pemilik_hak_cipta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pemilikhakcipta')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('kontak', models.CharField(max_length=50)),
                ('id_pemilik_hak_cipta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pemilikhakcipta')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('tipe', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.akun')),
                ('id_pemilik_hak_cipta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pemilikhakcipta')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('jumlah_lagu', models.IntegerField(default=0)),
                ('total_durasi', models.IntegerField()),
                ('id_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.label')),
            ],
        ),
        migrations.CreateModel(
            name='AkunPlayUserPlaylist',
            fields=[
                ('waktu', models.DateTimeField(primary_key=True, serialize=False)),
                ('email_pemain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.akun')),
                ('id_user_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='main.userplaylist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id_konten', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.konten')),
                ('total_play', models.IntegerField(default=0)),
                ('total_download', models.IntegerField(default=0)),
                ('id_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.album')),
                ('id_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Royalti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('id_pemilik_hak_cipta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pemilikhakcipta')),
                ('id_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.song')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id_konten', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.konten')),
                ('email_podcaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.podcaster')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id_episode', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=500)),
                ('durasi', models.IntegerField()),
                ('tanggal_rilis', models.DateField()),
                ('id_konten_podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.podcast')),
            ],
        ),
        migrations.CreateModel(
            name='AkunPlaySong',
            fields=[
                ('waktu', models.DateTimeField(primary_key=True, serialize=False)),
                ('email_pemain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.akun')),
                ('id_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.song')),
            ],
        ),
        migrations.CreateModel(
            name='SongwriterWriteSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_songwriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.songwriter')),
                ('id_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.song')),
            ],
            options={
                'unique_together': {('id_songwriter', 'id_song')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.playlist')),
                ('id_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.song')),
            ],
            options={
                'unique_together': {('id_playlist', 'id_song')},
            },
        ),
        migrations.CreateModel(
            name='DownloadedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_downloader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.premium')),
                ('id_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.song')),
            ],
            options={
                'unique_together': {('id_song', 'email_downloader')},
            },
        ),
    ]
